### ISSUE TITLE
rustic兼容

### ISSUE THREAD

**Issue by al-wei** [CanoeStudioOfficial/Classic-Bar-Legacy#2]
`Armor bar may not display correctly, disable Rustic's extra armor overlay amd restart the game. This is NOT a bug.`

聊天栏报错，但是我关了。

        # if enabled, allows the armor meter to go beyond one row
        # only one extra row will ever be rendered, because the armor stat is naturally capped at 30 [default: true]
        B:"Extra Armor HUD"=false

        # if enabled, adds a hud elemnt over the hunger meter to show armor toughness, if applicable [default: true]
        B:"Armor Toughness HUD"=false

**Comment by LonelyxiyaOVO** [comment]
等到月底时候修复，主要在学校，大多数没空

**Comment by Origins-Eternity** [comment]
> `Armor bar may not display correctly, disable Rustic's extra armor overlay amd restart the game. This is NOT a bug.`
> 
> 聊天栏报错，但是我关了。
> 
> ```
>     # if enabled, allows the armor meter to go beyond one row
>     # only one extra row will ever be rendered, because the armor stat is naturally capped at 30 [default: true]
>     B:"Extra Armor HUD"=false
> 
>     # if enabled, adds a hud elemnt over the hunger meter to show armor toughness, if applicable [default: true]
>     B:"Armor Toughness HUD"=false
> ```

![image](https://github.com/user-attachments/assets/6c1c6daf-e885-47cd-b407-90737f8899ca)
zhe'b只需在本模组配置文件中将Show Rustic warning一项改为false即可
